AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'node_modules/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - '.git/**/*'
    - '**/*.my'

Metrics/ModuleLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Lint/MissingCopEnableDirective:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false
